[project]
name = "Livt.ML"
version = "0.2.2"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "VecAddTest",
    "DotProductTest",
    "MatrixVectorMultiplicationTest",
    "Linear8x8Test",
    "ArgMax3Test",
    "ClassProjectionTest",
    "FixedTokenEmbeddingTest",
    "ReLUTest",
    "SigmoidLUTTest",
    "SiLUApproxTest",
    "SoftmaxApproxTest",
    "RMSNormTest",
    "KVCacheTest",
    "ScaledDotProductAttentionTest",
    "FeedForwardBlockTest",
    "TransformerBlockTest",
    "LinearRegressionTest"
]

[dependencies]
Livt.Math = "0.3.2"

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
