-- Copyright (C) 2026 Eccelerators GmbH
--
-- This code was generated by:
--
-- Livt Compiler v0.0.0-0000000
-- VHDL Extension for Livt v0.0.0-0000000
--
-- Further information at https://eccelerators.com/livt
--
-- Changes to this file may cause incorrect behavior and will be lost if the
-- code is regenerated.
library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;

use work.livt_lang_icomponent_package.all;
use work.livt_lang_icontext_package.all;
use work.livt_lang_package.all;
use work.livt_math_arithmetic_iintegerdivision_g_integer_sig_aa273db78b38_package.all;
use work.livt_math_arithmetic_integerdivision_g_32_sig_4fa0a627f162_package.all;
use work.livt_ml_numeric_scheduledrequantizeuint8_package.all;

entity livt_ml_numeric_scheduledrequantizeuint8_slice is
port (Clk: in std_logic; Rst: in std_logic;
applyrational_in : in t_scheduledrequantizeuint8_applyrational_in;
applyrational_out : out t_scheduledrequantizeuint8_applyrational_out;
clamp_in : in t_scheduledrequantizeuint8_clamp_in;
clamp_out : out t_scheduledrequantizeuint8_clamp_out);
end;
architecture rtl of livt_ml_numeric_scheduledrequantizeuint8_slice is begin
dut: entity work.livt_ml_numeric_scheduledrequantizeuint8 port map (ctor_lvt_context_in => (clk => Clk, rst => Rst, tickspersecond => to_unsigned(50000000,32), periodns => to_unsigned(20,32), hightimens => to_unsigned(10,32), lowtimens => to_unsigned(10,32)),
applyrational_in => applyrational_in,
applyrational_out => applyrational_out,
clamp_in => clamp_in,
clamp_out => clamp_out);
end;
